#!/bin/bash

pip3 install rpy2

cat > /tmp/install-stuff.R <<EOS
#!/usr/bin/Rscript --no-save

install.packages('devtools')
devtools::install_github('IRkernel/IRkernel')
IRkernel::installspec(user = FALSE, displayname = 'R 3.4')
IRkernel::installspec(user = FALSE, name = 'ir33', displayname = 'R 3.3')
IRkernel::installspec(user = FALSE, name = 'ir32', displayname = 'R 3.2')
EOS

chmod +x /tmp/install-stuff.R

/tmp/install-stuff.R
