#!/bin/sh
#
# Configured as part of the w205 Image build process

myip=$(hostname -I | awk '{print$1}')
cat <<EOF
------------------------------------------------------------------------
Welcome to your UC Berkeley MIDS w205 student cloud instance!

The "ufw" firewall is enabled. All ports except for 22 and 80 are blocked.

------------------------------------------------------------------------

EOF
