#!/bin/bash

if [ -e /root/.ssh/authorized_keys ]; then
   cp -au /root/.ssh /home/science
   chown -R science:science /home/science
fi

root_password_is_set() {
  local root_password="$(cat /etc/shadow | awk -F':' '/root/ { print $2 }')"
  [ "$root_password" != "*" ]
}

if root_password_is_set && id -u science; then

    # user gets the same inital pw as root
    usermod -p "$(cat /etc/shadow | awk -F':' '/root/ { print $2 }')" science

    # user must change pw at first login
    #passwd -e science
fi
